<template>
  <el-row style="background-color:#344a5f;">
    <el-col>
      <div id="content">
        <h1>404 Not Found</h1>
        <p>Sorry, the page you requested was Not Found </p>
      </div>

    </el-col>
  </el-row>
</template>
<style>
  #content {
    text-align: center;
    min-height: 400px;
    width: 400px;
    margin: 0 auto;
    background-color: #344a5f;
    color: #d4d9dd;
  }
</style>
