<template>
  <el-row style="background-color:#344a5f;">
    <el-col>
      <div id="content">
        <h1>404 Not Found</h1>
        <p>Sorry, the page you requested was Not Found </p>
      </div>

    </el-col>
  </el-row>
</template>
<script>
//  export default {
//    name: 'NotFound',
//    mounted () {
//      let script = document.createElement('script')
//      script.src = '//qzonestyle.gtimg.cn/qzone/hybrid/app/404/search_children.js'
//      script.charset = 'utf-8'
//      script.type = 'text/javascript'
//      script.homePageUrl ='https://maicss.com/'
//      script.homePageName = '返回首页'
//      document.querySelector('head').appendChild(script)
//    }
//  }
</script>
<style>
  #content {
    text-align: center;
    min-height: 400px;
    width: 400px;
    margin: 0 auto;
    background-color: #344a5f;
    color: #d4d9dd;
  }
</style>
